// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYfC7wW9HrDavLlt-wPgMCsQaLUomjXSc',
    appId: '1:704860501882:web:afecd73e589c62159648c3',
    messagingSenderId: '704860501882',
    projectId: 'my-holy-canvas',
    authDomain: 'my-holy-canvas.firebaseapp.com',
    storageBucket: 'my-holy-canvas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM8OXTSKU80oyPxiuLxcX4MnX8KxFVOK0',
    appId: '1:704860501882:android:94da1948da619c239648c3',
    messagingSenderId: '704860501882',
    projectId: 'my-holy-canvas',
    storageBucket: 'my-holy-canvas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCju5UaWF_zrQ1H1v0l2eaKw7-MtXMSUDI',
    appId: '1:704860501882:ios:73deec8e7acef8599648c3',
    messagingSenderId: '704860501882',
    projectId: 'my-holy-canvas',
    storageBucket: 'my-holy-canvas.firebasestorage.app',
    iosBundleId: 'com.holy.canvas.holyCanvas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCju5UaWF_zrQ1H1v0l2eaKw7-MtXMSUDI',
    appId: '1:704860501882:ios:73deec8e7acef8599648c3',
    messagingSenderId: '704860501882',
    projectId: 'my-holy-canvas',
    storageBucket: 'my-holy-canvas.firebasestorage.app',
    iosBundleId: 'com.holy.canvas.holyCanvas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYfC7wW9HrDavLlt-wPgMCsQaLUomjXSc',
    appId: '1:704860501882:web:0497c351dec0498d9648c3',
    messagingSenderId: '704860501882',
    projectId: 'my-holy-canvas',
    authDomain: 'my-holy-canvas.firebaseapp.com',
    storageBucket: 'my-holy-canvas.firebasestorage.app',
  );

}