// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBko4mBfKTrrLg4BjP7VK6E-jJzcDHG6Z0',
    appId: '1:706443073313:web:e8e3b2a7a7e621f79f9060',
    messagingSenderId: '706443073313',
    projectId: 'holy-word-studio',
    authDomain: 'holy-word-studio.firebaseapp.com',
    storageBucket: 'holy-word-studio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT3UZuglzHGEqve4Fk27KbMNBiDZpw-TI',
    appId: '1:706443073313:android:2598bab91792b0f69f9060',
    messagingSenderId: '706443073313',
    projectId: 'holy-word-studio',
    storageBucket: 'holy-word-studio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrYuLSoUxI-Lp8L3WeYfb8KpAsqlUki1s',
    appId: '1:706443073313:ios:63b777458f78e46c9f9060',
    messagingSenderId: '706443073313',
    projectId: 'holy-word-studio',
    storageBucket: 'holy-word-studio.firebasestorage.app',
    iosBundleId: 'com.holy.canvas.holyCanvas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrYuLSoUxI-Lp8L3WeYfb8KpAsqlUki1s',
    appId: '1:706443073313:ios:63b777458f78e46c9f9060',
    messagingSenderId: '706443073313',
    projectId: 'holy-word-studio',
    storageBucket: 'holy-word-studio.firebasestorage.app',
    iosBundleId: 'com.holy.canvas.holyCanvas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBko4mBfKTrrLg4BjP7VK6E-jJzcDHG6Z0',
    appId: '1:706443073313:web:f55650bd853dea109f9060',
    messagingSenderId: '706443073313',
    projectId: 'holy-word-studio',
    authDomain: 'holy-word-studio.firebaseapp.com',
    storageBucket: 'holy-word-studio.firebasestorage.app',
  );

}